### ISSUE TITLE
Version 2.0.2 fails to compile on Ubuntu with Swift 4.2

### ISSUE THREAD

**Issue by ksmandersen** [vapor/leaf#132]
I'm just leaving this here for anyone else who might run into this. Therefore I am going to close the issue.

If you're still running on version 2.0.2 compilation will fail under Ubuntu swift 4.2 with a SIL compilation error. The error you'll get will go something like this:

```
While emitting IR SIL function "@$S4Leaf15ParameterParser33_A7F42E4543F0554FB21DD60439F88E99LLC6BufferC14skipWhitespaceyyKF
```
The issue can be resolved by passing ``-Onone`` to the ``swiftc`` command. If you are using the heroku buildpack from kylef you must pass SWIFT_BUILD_FLAGS="-Xswiftc -Onone"
